---
tiers:
    -
        name: smoke
        order: 1
        ci_loop: '(daily)|(weekly)'
        description: >-
            Set of basic Functional tests to validate the OPNFV scenarios.
        testcases:
            -
                case_name: vping_ssh
                project_name: functest
                criteria: 100
                blocking: false
                description: >-
                    This test case verifies: 1) SSH to an instance using
                    floating IPs over the public network. 2) Connectivity
                    between 2 instances over a private network.
                dependencies:
                    installer: ''
                    scenario: '^((?!lxd).)*$'
                run:
                    module: 'functest.opnfv_tests.openstack.vping.vping_ssh'
                    class: 'VPingSSH'

            -
                case_name: vping_userdata
                project_name: functest
                criteria: 100
                blocking: false
                description: >-
                    This test case verifies:  1) Boot a VM with given userdata.
                    2) Connectivity between 2 instances over a private network.
                dependencies:
                    installer: ''
                    scenario: '^((?!lxd).)*$'
                run:
                    module:
                        'functest.opnfv_tests.openstack.vping.vping_userdata'
                    class: 'VPingUserdata'

            -
                case_name: tempest_smoke_serial
                project_name: functest
                criteria: 100
                blocking: false
                description: >-
                    This test case runs the smoke subset of the OpenStack
                    Tempest suite. The list of test cases is generated by
                    Tempest automatically and depends on the parameters of
                    the OpenStack deplopyment.
                dependencies:
                    installer: ''
                    scenario: ''
                run:
                    module: 'functest.opnfv_tests.openstack.tempest.tempest'
                    class: 'TempestCommon'
                    args:
                        mode: '^tempest\.(api|scenario).*\[.*\bsmoke\b.*\]$'
                        option:
                            - '--concurrency=1'

            -
                case_name: rally_sanity
                project_name: functest
                criteria: 100
                blocking: false
                description: >-
                    This test case runs a sub group of tests of the OpenStack
                    Rally suite in smoke mode.
                dependencies:
                    installer: ''
                    scenario: ''
                run:
                    module: 'functest.opnfv_tests.openstack.rally.rally'
                    class: 'RallySanity'

            -
                case_name: refstack_defcore
                project_name: functest
                criteria: 100
                blocking: false
                description: >-
                    This test case runs a sub group of tests of the OpenStack
                    Defcore testcases.
                dependencies:
                    installer: ''
                    scenario: ''
                run:
                    module:
                        'functest.opnfv_tests.openstack.refstack.refstack'
                    class: 'Refstack'

            -
                case_name: patrole
                project_name: functest
                criteria: 100
                blocking: false
                description: >-
                    Test suite from Patrole project.
                dependencies:
                    installer: ''
                    scenario: ''
                run:
                    module: 'functest.opnfv_tests.openstack.patrole.patrole'
                    class: 'Patrole'
                    args:
                        role: 'admin'
                        services:
                            - 'image'
                            - 'network'
                            - 'volume'
                        exclude:
                            - 'test_networks_multiprovider_rbac'

            -
                case_name: odl
                project_name: functest
                criteria: 100
                blocking: false
                description: >-
                    Test Suite for the OpenDaylight SDN Controller. It
                    integrates some test suites from upstream using
                    Robot as the test framework.
                dependencies:
                    installer: ''
                    scenario: 'odl'
                run:
                    module: 'functest.opnfv_tests.sdn.odl.odl'
                    class: 'ODLTests'
                    args:
                        suites:
                            - /src/odl_test/csit/suites/integration/basic
                            - /src/odl_test/csit/suites/openstack/neutron

            -
                case_name: snaps_smoke
                project_name: functest
                criteria: 100
                blocking: false
                description: >-
                    This test case contains tests that setup and destroy
                    environments with VMs with and without Floating IPs
                    with a newly created user and project. Set the config
                    value snaps.use_floating_ips (True|False) to toggle
                    this functionality. When the config value of
                    snaps.use_keystone is True, functest must have access to
                    the cloud's private network.

                dependencies:
                    installer: ''
                    scenario: '^((?!lxd).)*$'
                run:
                    module: 'functest.opnfv_tests.openstack.snaps.smoke'
                    class: 'SnapsSmoke'

            -
                case_name: neutron_trunk
                project_name: functest
                criteria: 100
                blocking: false
                description: >-
                    This test case runs the neutron trunk subtest of the
                    OpenStack Tempest suite. The list of test cases is
                    generated by Tempest having as input the relevant
                    testcase list file.
                dependencies:
                    installer: '(fuel)|(apex)|(compass)'
                    scenario: ''
                run:
                    module: 'functest.opnfv_tests.openstack.tempest.tempest'
                    class: 'TempestCommon'
                    args:
                        mode: 'neutron.tests.tempest.(api|scenario).test_trunk'
