#!/bin/bash
# -----------------------------------------------------------------------------
# ONOS remote command-line client.
# -----------------------------------------------------------------------------
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
#

[ ! -d "$ONOS_ROOT" ] && echo "ONOS_ROOT is not defined" >&2 && exit 1
. /root/.bashrc
. $ONOS_ROOT/tools/build/envDefaults
. $ONOS_ROOT/tools/test/bin/find-node.sh

[ "$1" = "-w" ] && shift && onos-wait-for-start $1

[ -n "$1" ] && OCI=$(find_node $1) && shift

if which client 1>/dev/null 2>&1 && [ -z "$ONOS_USE_SSH" ]; then
    # Use Karaf client only if we can and are allowed to
    unset KARAF_HOME
    client -h $OCI -u karaf "$@" 2>/dev/null
else
    # Otherwise use raw ssh; strict checking is off for dev environments only
    #ssh -p 8101 -o StrictHostKeyChecking=no $OCI "$@"
    sshpass -p karaf ssh -l karaf -p 8101 $OCI "$@"
fi
