#!/bin/bash

download-frozen-image-v2.sh /data/docker/functest \
  opnfv/functest-healthcheck:yoga \
  opnfv/functest-smoke:yoga \
  opnfv/functest-smoke-cntt:yoga \
  opnfv/functest-benchmarking:yoga \
  opnfv/functest-benchmarking-cntt:yoga \
  opnfv/functest-vnf:yoga
mkdir -p /data/images && wget -q -O- https://git.opnfv.org/functest/plain/functest/ci/download_images.sh?h=stable/yoga | sh -s -- /data/images && ls -1 /data/images/*
git init /home/debian/functest && \
(cd /home/debian/functest && \
  git fetch --tags https://git.opnfv.org/functest stable/yoga && \
  git checkout FETCH_HEAD) && \
chown -R 1000:1000 /home/debian/functest

exit 0
