#!/bin/bash

download-frozen-image-v2.sh /data/docker/functest \
  opnfv/functest-healthcheck:jerma \
  opnfv/functest-smoke:jerma \
  opnfv/functest-smoke-cntt:jerma \
  opnfv/functest-benchmarking:jerma \
  opnfv/functest-benchmarking-cntt:jerma \
  opnfv/functest-vnf:jerma
mkdir -p /data/images && wget -q -O- https://git.opnfv.org/functest/plain/functest/ci/download_images.sh?h=stable/jerma | sh -s -- /data/images && ls -1 /data/images/*
git init /home/debian/functest && \
(cd /home/debian/functest && \
  git fetch --tags https://git.opnfv.org/functest stable/jerma && \
  git checkout FETCH_HEAD) && \
chown -R 1000:1000 /home/debian/functest

exit 0
