diff --git a/docker/core/Dockerfile b/docker/core/Dockerfile
index 165c8a7..aedbb19 100644
--- a/docker/core/Dockerfile
+++ b/docker/core/Dockerfile
@@ -1,4 +1,4 @@
-FROM alpine:3.6
+FROM multiarch/alpine:arm64-latest-stable

 ARG BRANCH=master
 ARG OPENSTACK_TAG=stable/pike

