From 3c33900c6e97ec999bb0272302d078dd7fa2b801 Mon Sep 17 00:00:00 2001
From: Delia Popescu <delia.popescu@enea.com>
Date: Fri, 8 Sep 2017 15:36:01 +0300
Subject: [PATCH] Create patch for functest-core Dockerfile

Signed-off-by: Delia Popescu <delia.popescu@enea.com>
---
 docker/core/Dockerfile | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/docker/core/Dockerfile b/docker/core/Dockerfile
index c5766da..ed0756f 100644
--- a/docker/core/Dockerfile
+++ b/docker/core/Dockerfile
@@ -1,4 +1,5 @@
-FROM alpine:3.6
+FROM multiarch/alpine:aarch64-latest-stable
+
 
 ARG BRANCH=master
 ARG OPENSTACK_TAG=stable/ocata
-- 
2.9.4

