---
compute:
    max_microversion: 2.88
compute-feature-enabled:
    attach_encrypted_volume: false
    block_migration_for_live_migration: false
    block_migrate_cinder_iscsi: false
    change_password: false
    cold_migration: true
    config_drive: true
    console_output: true
    disk_config: true
    enable_instance_password: true
    hostname_fqdn_sanitization: false
    interface_attach: true
    live_migration: true
    live_migrate_back_and_forth: false
    metadata_service: true
    pause: true
    personality: false
    rdp_console: false
    rescue: true
    resize: true
    scheduler_available_filters: "AvailabilityZoneFilter,ComputeFilter,\
      ComputeCapabilitiesFilter,ImagePropertiesFilter,ServerGroupAntiAffinityFilter,\
      ServerGroupAffinityFilter,SameHostFilter,DifferentHostFilter"
    serial_console: false
    shelve: true
    snapshot: true
    spice_console: false
    suspend: true
    swap_volume: false
    vnc_console: true
    volume_backed_live_migration: false
    volume_multiattach: false
identity:
    auth_version: v3
    user_unique_last_password_count: 2
    user_lockout_duration: 10
    user_lockout_failure_attempts: 2
identity-feature-enabled:
    trust: true
    api_v2: false
    api_v2_admin: false
    security_compliance: true
    federation: false
    external_idp: false
    project_tags: true
    application_credentials: true
    access_rules: true
image-feature-enabled:
    api_v2: true
    api_v1: false
    import_image: false
network-feature-enabled:
    port_admin_state_change: true
    port_security: true
placement:
    max_microversion: 1.36
validation:
    image_ssh_user: cirros
    ssh_timeout: 196
    ip_version_for_ssh: 4
    run_validation: true
volume:
    max_microversion: 3.64
    storage_protocol: ceph
    manage_volume_ref: source-name,volume-%s
    manage_snapshot_ref: source-name,snapshot-%s
volume-feature-enabled:
    multi_backend: false
    backup: true
    snapshot: true
    clone: true
    manage_snapshot: true
    manage_volume: true
    extend_attached_volume: true
    extend_attached_encrypted_volume: false
    consistency_group: false
    volume_revert: true
load_balancer:
    test_with_ipv6: false
neutron_plugin_options:
    agent_availability_zone: nova
    available_type_drivers: flat,geneve,vlan,gre,local,vxlan
    provider_vlans: public,
    create_shared_resources: true
object-storage-feature-enabled:
    discoverable_apis: "account_quotas,formpost,bulk_upload,bulk_delete,\
      tempurl,crossdomain,container_quotas,staticweb,account_quotas,slo"
    object_versioning: true
    discoverability: true
    tempurl_digest_hashlib: sha1
heat_plugin:
    skip_functional_test_list: EncryptionVolTypeTest
    skip_scenario_test_list: "AodhAlarmTest,SoftwareConfigIntegrationTest,\
      VolumeBackupRestoreIntegrationTest,CfnInitIntegrationTest,\
      LoadBalancerTest"
    auth_version: 3
heat_features_enabled:
    multi_cloud: false
rbac:
    enable_rbac: true
