---
compute:
    max_microversion: 2.79
compute-feature-enabled:
    attach_encrypted_volume: false
    block_migration_for_live_migration: false
    block_migrate_cinder_iscsi: false
    change_password: false
    cold_migration: true
    config_drive: true
    console_output: true
    disk_config: true
    enable_instance_password: true
    interface_attach: true
    live_migration: true
    live_migrate_back_and_forth: false
    metadata_service: true
    pause: true
    personality: false
    rdp_console: false
    rescue: true
    resize: true
    scheduler_available_filters: "RetryFilter,AvailabilityZoneFilter,\
      ComputeFilter,ComputeCapabilitiesFilter,ImagePropertiesFilter,\
      ServerGroupAntiAffinityFilter,ServerGroupAffinityFilter,SameHostFilter,\
      DifferentHostFilter"
    serial_console: false
    shelve: true
    snapshot: true
    spice_console: false
    suspend: true
    swap_volume: false
    vnc_console: false
    volume_backed_live_migration: false
    volume_multiattach: false
identity:
    user_unique_last_password_count: 2
    user_lockout_duration: 10
    user_lockout_failure_attempts: 2
identity-feature-enabled:
    trust: true
    api_v2: false
    api_v2_admin: false
    security_compliance: true
    federation: false
    external_idp: false
    project_tags: true
    application_credentials: true
image-feature-enabled:
    api_v2: true
    api_v1: false
placement:
    max_microversion: 1.36
volume:
    max_microversion: 3.59
    storage_protocol: ceph
    manage_volume_ref: source-name,volume-%s
    manage_snapshot_ref: source-name,snapshot-%s
volume-feature-enabled:
    multi_backend: false
    backup: true
    snapshot: true
    clone: true
    manage_snapshot: true
    manage_volume: true
    extend_attached_volume: false
    consistency_group: false
    volume_revert: true
load_balancer:
    test_with_noop: true
neutron_plugin_options:
    agent_availability_zone: nova
    available_type_drivers: flat,geneve,vlan,gre,local,vxlan
    provider_vlans: foo,
