general:
    directories:
        # Relative to the path where the repo is cloned:
        dir_vping:         testcases/vPing/CI/libraries/
        dir_odl:           testcases/Controllers/ODL/CI/
        dir_rally:         testcases/VIM/OpenStack/CI/libraries/
        dir_rally_scn:     testcases/VIM/OpenStack/CI/rally_cert/
        dir_tempest_cases: testcases/VIM/OpenStack/CI/custom_tests/
        dir_vIMS:          testcases/vIMS/CI/
        dir_onos:          testcases/Controllers/ONOS/Teston/CI/

        # Absolute path
        dir_repos:          /home/opnfv/repos
        dir_repo_functest:  /home/opnfv/repos/functest
        dir_repo_rally:     /home/opnfv/repos/rally
        dir_repo_tempest:   /home/opnfv/repos/tempest
        dir_repo_releng:    /home/opnfv/repos/releng
        dir_repo_vims_test: /home/opnfv/repos/vims-test
        dir_repo_bgpvpn:    /home/opnfv/repos/bgpvpn
        dir_repo_onos:      /home/opnfv/repos/onos
        dir_repo_promise:   /home/opnfv/repos/promise
        dir_repo_doctor:    /home/opnfv/repos/doctor
        dir_repo_ovno:      /home/opnfv/repos/ovno
        dir_functest:       /home/opnfv/functest
        dir_results:        /home/opnfv/functest/results
        dir_functest_conf:  /home/opnfv/functest/conf
        dir_rally_res:      /home/opnfv/functest/results/rally/
        dir_functest_data:  /home/opnfv/functest/data
        dir_vIMS_data:      /home/opnfv/functest/data/vIMS
        dir_rally_inst:     /home/opnfv/.rally

    openstack:
        image_name: functest-img
        image_file_name:  cirros-0.3.4-x86_64-disk.img
        image_disk_format:  qcow2

        # Private network for functest. Will be created by config_functest.py
        neutron_private_net_name: functest-net
        neutron_private_subnet_name: functest-subnet
        neutron_private_subnet_cidr: 192.168.120.0/24
        neutron_private_subnet_start: 192.168.120.2
        neutron_private_subnet_end: 192.168.120.254
        neutron_private_subnet_gateway: 192.168.120.254
        neutron_router_name: functest-router

vping:
    ping_timeout:   200
    vm_flavor: m1.small # adapt to your environment
    vm_name_1: opnfv-vping-1
    vm_name_2: opnfv-vping-2
    image_name: functest-vping
    vping_private_net_name: vping-net
    vping_private_subnet_name: vping-subnet
    vping_private_subnet_cidr: 192.168.130.0/24
    vping_router_name: vping-router
    vping_sg_name: vPing-sg
    vping_sg_descr: Security group for vPing test case

tempest:
    identity:
        tenant_name: tempest
        tenant_description: Tenant for Tempest test suite
        user_name: tempest
        user_password: tempest
    private_net_name: tempest-net
    private_subnet_name: tempest-subnet
    private_subnet_cidr: 192.168.150.0/24
    router_name: tempest-router

rally:
    deployment_name: opnfv-rally

vIMS:
    general:
        tenant_name: vIMS
        tenant_description: vIMS Functionality Testing
        images:
            ubuntu:
                image_url: 'http://cloud-images.ubuntu.com/trusty/current/trusty-server-cloudimg-amd64-disk1.img'
                image_name: ubuntu_14.04
            centos:
                image_url: 'http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1510.qcow2'
                image_name: centos_7
    cloudify:
        blueprint:
            url: https://github.com/boucherv-orange/cloudify-manager-blueprints.git
            branch: "3.3-build"
        requierments:
            ram_min: 3000
            os_image: centos_7
        inputs:
            keystone_username: ""
            keystone_password: ""
            keystone_tenant_name: ""
            keystone_url: ""
            manager_public_key_name: 'manager-kp'
            agent_public_key_name: 'agent-kp'
            image_id: ""
            flavor_id: "3"
            external_network_name: ""
            ssh_user: centos
            agents_user: ubuntu
    clearwater:
        blueprint:
            file_name: 'openstack-blueprint.yaml'
            name: "clearwater-opnfv"
            destination_folder: "opnfv-cloudify-clearwater"
            url: 'https://github.com/Orange-OpenSource/opnfv-cloudify-clearwater.git'
            branch: "stable"
        deployment-name: 'clearwater-opnfv'
        requierments:
            ram_min: 1700
            os_image: ubuntu_14.04
        inputs:
            image_id: ''
            flavor_id: ''
            agent_user: 'ubuntu'
            external_network_name: ''
            public_domain: clearwater.opnfv
ONOS:
    general:
        onosbench_username: 'root'
        onosbench_password: 'root'
        onoscli_username: 'root'
        onoscli_password: 'root'
        runtimeout: 300
    environment:
        OCT: '10.20.0.1'
        OC1: '10.20.0.7'
        OC2: '10.20.0.7'
        OC3: '10.20.0.7'
        OCN: '10.20.0.4'
        OCN2: '10.20.0.5'
        installer_master: '10.20.0.2'
        installer_master_username: 'root'
        installer_master_password: 'r00tme'

promise:
    general:
        tenant_name: promise
        tenant_description: promise Functionality Testing
        user_name: promiser
        user_pwd: test
        image_name: promise-img
        flavor_name: promise-flavor
        flavor_vcpus: 1
        flavor_ram: 512
        flavor_disk: 0
        network_name: promise-net
        subnet_name: promise-subnet
        subnet_cidr: 192.168.121.0/24
        router_name: promise-router

results:
    test_db_url: http://testresults.opnfv.org/testapi

# to be maintained...
# the execution order is important as some tests may be more destructive than others
# and if vPing is failing is usually not needed to continue...
test_exec_priority:
    1: healthcheck
    2: vping_ssh
    3: vping_userdata
    4: tempest
    5: odl
    6: onos
    7: ovno
    8: doctor
    9: promise
    10: odl-vpnservice
    11: bgpvpn
    #11: openstack-neutron-bgpvpn-api-extension-tests
    12: vims
    13: rally


########################################################################
# This part lists the dependencies of the tests
#
# it is used to manage the complexity of the possible combinations
#
# 17 projects have been declared for Brahmaputra (D Milestone)
# 89 testcases are associated with these 17 projects
#
# in B-Release, Functest deals with 6 companion projects:
# - congress
# - doctor
# - ovno
# - policyTest
# - promise
# - sdnvpn
#
# constraints may be declared at the testcase or the test project level
#
# By default we consider that all the tests can be run on any configuration
#
# we defined 2 constraints
# - installer (e.g. my test can be run only with installer Compass)
# possible values: apex, compass, fuel, joid
#
# - the scenario: it described a specif installation
#    os-<controller>-<nfvfeature>-<mode>[-<extrastuff>]
# With parameters:
#    controller=(nosdn|odl_l3|odl_l2|onos|ocl)
#       No odl_l3 today
#    nfvfeature=(kvm|ovs|dpdk|nofeature)
#       '_' list separated.
#    mode=(ha|noha)
#    extrastuff=(none)
#       Optional field - Not used today#
#
# ref:https://gerrit.opnfv.org/gerrit/#/c/6323/7/jjb/joid/joid-deploy.sh (L72-82)
#  e.g my test is only possible with OVS 2.3.2 on odl
#
# in functest, we indicate the regex pattern to be checked towards the scenario
# e.g. odl-vpn_service-tests can be run if and only if
#                                - installer is fuel
#                                - scenario contains the name ovs and odl
#
#######################################################################
test-dependencies:
    doctor:
        installer: 'apex'
    functest:
        vims:
            scenario: '(ocl)|(nosdn)|^(os-odl)((?!bgpvpn).)*$'
        healthcheck:
        vping_ssh:
            scenario: '^((?!bgpvpn).)*$'
        vping_userdata:
        tempest:
        rally:
        odl:
            scenario: 'odl'
        onos:
            scenario: 'onos'
    promise:
        installer: '(fuel)|(joid)'
    ovno:
        scenario: 'ocl'
    policy-test:
        scenario: 'odl'
    sdnvpn:
        bgpvpn:
            installer: '(fuel)|(apex)'
            scenario: 'bgpvpn'
            # this execute the tempest tests of networking-bgpvpn
